import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

/** Merge conditional class names, with later Tailwind utilities winning. */
export const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));

/** Compact number formatting: 2350000 -> "2.35M". */
export const formatNumber = (n: number | null | undefined) => {
  if (n == null || !Number.isFinite(n)) return '—';
  const abs = Math.abs(n);
  if (abs >= 1e9) return (n / 1e9).toFixed(2) + 'B';
  if (abs >= 1e6) return (n / 1e6).toFixed(2) + 'M';
  if (abs >= 1e3) return (n / 1e3).toFixed(1) + 'K';
  return Number.isInteger(n) ? String(n) : n.toFixed(1);
};

/** Bits-per-second with SI unit suffix: 2350000 -> "2.35 Mbps". */
export const formatBits = (bps: number | null | undefined) => {
  if (bps == null || !Number.isFinite(bps)) return '—';
  const abs = Math.abs(bps);
  if (abs >= 1e9) return (bps / 1e9).toFixed(2) + ' Gbps';
  if (abs >= 1e6) return (bps / 1e6).toFixed(2) + ' Mbps';
  if (abs >= 1e3) return (bps / 1e3).toFixed(1) + ' Kbps';
  return bps.toFixed(0) + ' bps';
};

/** Duration given in MILLISECONDS: 0.4 -> "0.4ms", 300000 -> "5m 0s". */
export const formatDuration = (ms: number | null | undefined) => {
  if (ms == null || !Number.isFinite(ms)) return '—';
  if (ms < 1000) return (ms < 10 ? ms.toFixed(1) : ms.toFixed(0)) + 'ms';
  const totalSec = ms / 1000;
  if (totalSec < 60) return totalSec.toFixed(1) + 's';
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor((totalSec % 3600) / 60);
  const s = Math.floor(totalSec % 60);
  return h > 0 ? `${h}h ${m}m` : `${m}m ${s}s`;
};

let __idCounter = 0;
/** Short, collision-resistant id for generated mock records. */
export const generateId = () =>
  (Date.now().toString(36) + (__idCounter++).toString(36) + Math.random().toString(36).slice(2, 8)).slice(-12);

export const formatUptime = (s: number) => {
  const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;
  return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;
};
export const formatBytes = (b: number) => b>=1e9?(b/1e9).toFixed(1)+' GB':b>=1e6?(b/1e6).toFixed(1)+' MB':b>=1e3?(b/1e3).toFixed(0)+' KB':b+' B';

export const CLASS_COLORS: Record<string,string> = {
  'DDoS':'#f04050','C2 Beaconing':'#e8a020','DGA':'#8060f0','DNS Tunnel':'#5a8cf0',
  'TLS Malware':'#10d4e8','Recon':'#6a7a8c','Exfiltration':'#20c070',
};

// evidence features per threat class — what the ML models actually output
export const CLASS_EVIDENCE: Record<string, {key:string;unit:string}[]> = {
  'DDoS': [{key:'packet_rate',unit:'pps'},{key:'syn_ack_ratio',unit:''},{key:'source_entropy',unit:''},{key:'amplification_ratio',unit:'x'}],
  'C2 Beaconing': [{key:'periodicity_score',unit:''},{key:'dominant_period',unit:'s'},{key:'inter_arrival_cv',unit:''},{key:'jitter',unit:'ms'}],
  'DGA': [{key:'domain_entropy',unit:'bits'},{key:'bigram_likelihood',unit:''},{key:'digit_ratio',unit:'%'},{key:'consonant_vowel_ratio',unit:''}],
  'TLS Malware': [{key:'extensions_count',unit:''},{key:'ciphers_count',unit:''},{key:'min_pkt_size',unit:'B'},{key:'median_pkt_size',unit:'B'}],
  'Recon': [{key:'unique_dst_ports',unit:''},{key:'unique_dst_hosts',unit:''},{key:'syn_ack_ratio',unit:''},{key:'scan_duration',unit:'s'}],
  'Exfiltration': [{key:'byte_ratio_outbound',unit:':1'},{key:'total_bytes',unit:'B'},{key:'avg_pkt_size',unit:'B'},{key:'flow_duration',unit:'s'}],
};

// BENCHMARK and MODELS constants removed deliberately.
//
// They hardcoded DGA "auc: .9991, testAuc: 1.0" and a throughput of 88.6 fps /
// p50 12.93 ms. The AUC figures were invalidated by the team's own audit (the
// old corpus was separable by domain length alone) and the throughput numbers
// came from mixing two different benchmark runs. Because the UI read these
// constants, the dashboard asserted numbers the deck had already corrected.
//
// Model metrics now come from GET /api/v1/models (generated by
// scripts/regenerate_evaluation.py) and throughput from
// GET /api/v1/metrics/throughput, both measured rather than stored.
